### ISSUE TITLE
norm_ ED value increases instead of decreasing

### ISSUE THREAD

**Issue by my-Circle** [AprilYapingZhang/Seq2SeqAdapt#10]
Hello, in the process of training according to the readme file, I have encountered a problem that is difficult to solve, the training accuracy is increasing, but norm_ED value is also rising, and has exceeded 10000 iteration, but still has no downward trend.I really hope to get your guidance，thank you very much!

**Comment by AprilYapingZhang** [comment]
Yes, it is the right trend.  Actually, the norm_ED =1- NED in our code ,  you can see the implemented code in utils.py line 132.

**Comment by my-Circle** [comment]
Very thank you for your prompt reply！So maybe can I change the "if current_norm_ED < best_norm_ED" condition of saving the optimal model in line 340 of the file train_da_global_local_selected.py to "if current_norm_ED ＞ best_norm_ED"？
If I don't change it, the training process will always save the original model, because the more I train ,the higher the norm_ED value.As I mentioned in issue 9
Thank you again for your reply! It helped me a lot!

**Comment by AprilYapingZhang** [comment]
Yes, you also can use accuracy to choose the best model

**Comment by my-Circle** [comment]
thank you very much！
