### ISSUE TITLE
How do you calculate CORAL?

### ISSUE THREAD

**Issue by WangKK1996** [AprilYapingZhang/Seq2SeqAdapt#2]
hello, thanks for your amazing work.
when I read your paper there's something confused me. you said you calculate the domain differerence by using CORAL, do you calculate it by sample or by batch?
If you calculate it by batch, than the dimension will be 3, how to caculate the convariance?
If you calculate it by sample , what if the $y_k$s are totally different from source image and target image?

**Comment by WangKK1996** [comment]
hello, me again;)
Recentlly I read your code and tried to find out how you calculate CORAL, but in your code I found you choose to calcuate domain difference by GAN loss instead of CORAL, so this question is still confusing me. I tried to use CORAL dirrectly on the output of local feature and global feature but the result was worse than GAN loss, so I was wondering if i did something wrong.

**Comment by AprilYapingZhang** [comment]
This repo is an extended version of the original conference version.
Indeed, the original CORAL loss of SSDAN is only calculated on local level.
The original SSDAN code could be referred to https://github.com/nieshaoshuai/Seq2seqAdapt_paper.

**Comment by AprilYapingZhang** [comment]
> hello, me again;)
> Recentlly I read your code and tried to find out how you calculate CORAL, but in your code I found you choose to calcuate domain difference by GAN loss instead of CORAL, so this question is still confusing me. I tried to use CORAL dirrectly on the output of local feature and global feature but the result was worse than GAN loss, so I was wondering if i did something wrong.

This repo is an extended version of the original conference version.
Indeed, the original CORAL loss of SSDAN is only calculated on local level.
The original SSDAN code could be referred to https://github.com/nieshaoshuai/Seq2seqAdapt_paper.

**Comment by WangKK1996** [comment]
> This repo is an extended version of the original conference version.
> Indeed, the original CORAL loss of SSDAN is only calculated on local level.
> The original SSDAN code could be referred to https://github.com/nieshaoshuai/Seq2seqAdapt_paper.

thank you for your reply! I'll check the official version, and thank you for sharing this pyrorch version too
