### ISSUE TITLE
No improvement in accuracy during training

### ISSUE THREAD

**Issue by XueyingDing123** [AprilYapingZhang/Seq2SeqAdapt#6]
Hello, I found that the recognition accuracy has not been improved when I trained according to the readme.  I am wondering if friends with the same problems or author could provide some suggestions. Thank you very much!

**Comment by AprilYapingZhang** [comment]
The recognition accuracy rises in fluctuation during training process, due to the adversarial traning between feature domain adaptation and decoding loss.  You can observe the improvement of performance after 10000 training steps.
