### ISSUE TITLE
Experiment HT->ST

### ISSUE THREAD

**Issue by XueyingDing123** [AprilYapingZhang/Seq2SeqAdapt#8]
Hello, thank you for your previous reply. I also want to ask which scene text (training set of synthetic text, COMB or other datasets) is selected in the experiment with handwritten text as the source domain and scene text as the target domain (HT - > ST).  In addition, does this experiment need to use the pretrained source model to train a domain adaptive model? Looking forward to your reply again, thank you!

**Comment by AprilYapingZhang** [comment]
Yes, the pretrained source model is needed
